module.exports = {
  GETTING_PIN_VERIFIED: 'GETTING_PIN_VERIFIED',
  GETTING_PIN_VERIFIED_FAILURE: 'GETTING_PIN_VERIFIED_FAILURE',
  GETTING_PIN_VERIFIED_SUCCESS: 'GETTING_PIN_VERIFIED_SUCCESS',
  SAVE_ID: 'SAVE_ID',
  RESET_DATA: 'RESET_DATA',
  RESET_ERROR: 'RESET_ERROR',
  INITIAL_STATE: { isPinVerified: false, status: 'no data', error: null, loading: false, vehicleId: null }
}
