module.exports = {
  GETTING_INFO: 'GETTING_INFO',
  GETTING_INFO_SUCCESS: 'GETTING_INFO_SUCCESS',
  GETTING_INFO_FAILURE: 'GETTING_INFO_FAILURE',
  GETTING_XML: 'GETTING_XML',
  GETTING_XML_SUCCESS: 'GETTING_XML_SUCCESS',
  GETTING_XML_FAILURE: 'GETTING_XML_FAILURE',
  SENDING_INFO: 'SENDING_INFO',
  SENDING_INFO_FAILURE: 'SENDING_INFO_FAILURE',
  SENDING_INFO_SUCCESS: 'SENDING_INFO_SUCCESS',
  GETTING_PIN_VERIFIED: 'GETTING_PIN_VERIFIED',
  GETTING_PIN_VERIFIED_FAILURE: 'GETTING_PIN_VERIFIED_FAILURE',
  GETTING_PIN_VERIFIED_SUCCESS: 'GETTING_PIN_VERIFIED_SUCCESS',
  RESET_INFO: 'RESET_INFO',
  INITIAL_STATE: { data: null, status: null, isPinVerified: false, error: null, loading: null }
}
