module.exports = {
  GETTING_INFO: 'GETTING_INFO',
  GETTING_INFO_SUCCESS: 'GETTING_INFO_SUCCESS',
  GETTING_INFO_FAILURE: 'GETTING_INFO_FAILURE',
  GETTING_XML: 'GETTING_XML',
  GETTING_XML_SUCCESS: 'GETTING_XML_SUCCESS',
  GETTING_XML_FAILURE: 'GETTING_XML_SUCCESS',
  SENDDING_INFO: 'SENDING_INFO_SUCCESS',
  SENDING_INFO_FAILURE: 'SENDING_INFO_FAILURE',
  SENDING_INFO_SUCCESS: 'SENDING_INFO_SUCCESS',
  INITIAL_STATE: { data: null, status: null, error: null, loading: null }
}
