module.exports = {
  GETTING_INFO: 'GETTING_INFO',
  GETTING_INFO_SUCCESS: 'GETTING_INFO_SUCCESS',
  GETTING_INFO_FAILURE: 'GETTING_INFO_FAILURE',
  REINIT_STATE: 'REINIT_STATE',
  INITIAL_STATE: { data: null, status: null, error: null, loading: null }
}
