module.exports = {
  getting: {
    GETTING_SUPPLY_INFO: 'GETTING_SUPPLY_INFO',
    GETTING_SUPPLY_INFO_SUCCESS: 'GETTING_SUPPLY_INFO_SUCCESS',
    GETTING_SUPPLY_INFO_FAILURE: 'GETTING_SUPPLY_INFO_FAILURE'
  },
  sending: {
    SENDING_SUPPLY_INFO: 'SENDING_SUPPLY_INFO',
    SENDING_SUPPLY_INFO_FAILURE: 'SENDING_SUPPLY_INFO_FAILURE',
    SENDING_SUPPLY_INFO_SUCCESS: 'SENDING_SUPPLY_INFO_SUCCESS'
  },
  liters: {
    GETTING_LITERS_SUCCESS: 'GETTING_LITERS_SUCCESS',
    GETTING_LITERS: 'GETTING_LITERS',
    GETTING_LITERS_FAILURE: 'GETTING_LITERS_FAILURE'
  },
  RESET_DATA: 'RESET_DATA',
  RESET_ERROR: 'RESET_ERROR',
  INITIAL_STATE: { data: null, status: 'no data', error: null, loading: false, liters: '' }
}
